#include "gui_elements.h"

#define KEYBOARD_KEY_WIDTH (24)
#define KEYBOARD_KEY_HEIGHT (28)
#define KEYBOARD_ROW1_X (0)
#define KEYBOARD_ROW2_X (0)
#define KEYBOARD_ROW3_X (KEYBOARD_KEY_WIDTH/2)
#define KEYBOARD_ROW4_X (KEYBOARD_KEY_WIDTH/2)
#define KEYBOARD_Y_START (6)
#define KEYBOARD_LABEL_SCALE (2)

#define KEYPAD_KEY_WIDTH (51)
#define KEYPAD_KEY_HEIGHT (30)
#define KEYPAD_X_START (25)
#define KEYPAD_X_GAP (17)
#define KEYPAD_Y_START (6)
#define KEYPAD_Y_GAP (6)
#define KEYPAD_LABEL_SCALE (4)

const InterfaceButton_t keypad_buttons[12] =
{
	{ .id = '1', KEYPAD_LABEL_SCALE, .width = KEYPAD_KEY_WIDTH, .height = KEYPAD_KEY_HEIGHT, .x = KEYPAD_X_START,                                         .y = KEYPAD_Y_START,                                          .label = "1" },
	{ .id = '2', KEYPAD_LABEL_SCALE, .width = KEYPAD_KEY_WIDTH, .height = KEYPAD_KEY_HEIGHT, .x = KEYPAD_X_START + (KEYPAD_KEY_WIDTH + KEYPAD_X_GAP),     .y = KEYPAD_Y_START,                                          .label = "2" },
	{ .id = '3', KEYPAD_LABEL_SCALE, .width = KEYPAD_KEY_WIDTH, .height = KEYPAD_KEY_HEIGHT, .x = KEYPAD_X_START + ((KEYPAD_KEY_WIDTH + KEYPAD_X_GAP)*2), .y = KEYPAD_Y_START,                                          .label = "3" },
	{ .id = '4', KEYPAD_LABEL_SCALE, .width = KEYPAD_KEY_WIDTH, .height = KEYPAD_KEY_HEIGHT, .x = KEYPAD_X_START,                                         .y = KEYPAD_Y_START + (KEYPAD_KEY_HEIGHT + KEYPAD_Y_GAP),     .label = "4" },
	{ .id = '5', KEYPAD_LABEL_SCALE, .width = KEYPAD_KEY_WIDTH, .height = KEYPAD_KEY_HEIGHT, .x = KEYPAD_X_START + KEYPAD_KEY_WIDTH + KEYPAD_X_GAP,       .y = KEYPAD_Y_START + (KEYPAD_KEY_HEIGHT + KEYPAD_Y_GAP),     .label = "5" },
	{ .id = '6', KEYPAD_LABEL_SCALE, .width = KEYPAD_KEY_WIDTH, .height = KEYPAD_KEY_HEIGHT, .x = KEYPAD_X_START + ((KEYPAD_KEY_WIDTH + KEYPAD_X_GAP)*2), .y = KEYPAD_Y_START + (KEYPAD_KEY_HEIGHT + KEYPAD_Y_GAP),     .label = "6" },
	{ .id = '7', KEYPAD_LABEL_SCALE, .width = KEYPAD_KEY_WIDTH, .height = KEYPAD_KEY_HEIGHT, .x = KEYPAD_X_START,                                         .y = KEYPAD_Y_START + ((KEYPAD_KEY_HEIGHT + KEYPAD_Y_GAP)*2), .label = "7" },
	{ .id = '8', KEYPAD_LABEL_SCALE, .width = KEYPAD_KEY_WIDTH, .height = KEYPAD_KEY_HEIGHT, .x = KEYPAD_X_START + KEYPAD_KEY_WIDTH + KEYPAD_X_GAP,       .y = KEYPAD_Y_START + ((KEYPAD_KEY_HEIGHT + KEYPAD_Y_GAP)*2), .label = "8" },
	{ .id = '9', KEYPAD_LABEL_SCALE, .width = KEYPAD_KEY_WIDTH, .height = KEYPAD_KEY_HEIGHT, .x = KEYPAD_X_START + ((KEYPAD_KEY_WIDTH + KEYPAD_X_GAP)*2), .y = KEYPAD_Y_START + ((KEYPAD_KEY_HEIGHT + KEYPAD_Y_GAP)*2), .label = "9" },
	{ .id = '*', KEYPAD_LABEL_SCALE, .width = KEYPAD_KEY_WIDTH, .height = KEYPAD_KEY_HEIGHT, .x = KEYPAD_X_START,                                         .y = KEYPAD_Y_START + ((KEYPAD_KEY_HEIGHT + KEYPAD_Y_GAP)*3), .label = "*" },
	{ .id = '0', KEYPAD_LABEL_SCALE, .width = KEYPAD_KEY_WIDTH, .height = KEYPAD_KEY_HEIGHT, .x = KEYPAD_X_START + KEYPAD_KEY_WIDTH + KEYPAD_X_GAP,       .y = KEYPAD_Y_START + ((KEYPAD_KEY_HEIGHT + KEYPAD_Y_GAP)*3), .label = "0" },
	{ .id = '#', KEYPAD_LABEL_SCALE, .width = KEYPAD_KEY_WIDTH, .height = KEYPAD_KEY_HEIGHT, .x = KEYPAD_X_START + ((KEYPAD_KEY_WIDTH + KEYPAD_X_GAP)*2), .y = KEYPAD_Y_START + ((KEYPAD_KEY_HEIGHT + KEYPAD_Y_GAP)*3), .label = "#" },
};

const InterfaceButton_t keyboard_buttons[40] =
{
    { .id = '1', KEYBOARD_LABEL_SCALE, .width = KEYBOARD_KEY_WIDTH, .height = KEYBOARD_KEY_HEIGHT, .x = KEYBOARD_ROW1_X,             .y = KEYBOARD_Y_START, .label = "1" },
    { .id = '2', KEYBOARD_LABEL_SCALE, .width = KEYBOARD_KEY_WIDTH, .height = KEYBOARD_KEY_HEIGHT, .x = KEYBOARD_ROW1_X+KEYBOARD_KEY_WIDTH,   .y = KEYBOARD_Y_START, .label = "2" },
    { .id = '3', KEYBOARD_LABEL_SCALE, .width = KEYBOARD_KEY_WIDTH, .height = KEYBOARD_KEY_HEIGHT, .x = KEYBOARD_ROW1_X+KEYBOARD_KEY_WIDTH*2, .y = KEYBOARD_Y_START, .label = "3" },
    { .id = '4', KEYBOARD_LABEL_SCALE, .width = KEYBOARD_KEY_WIDTH, .height = KEYBOARD_KEY_HEIGHT, .x = KEYBOARD_ROW1_X+KEYBOARD_KEY_WIDTH*3, .y = KEYBOARD_Y_START, .label = "4" },
    { .id = '5', KEYBOARD_LABEL_SCALE, .width = KEYBOARD_KEY_WIDTH, .height = KEYBOARD_KEY_HEIGHT, .x = KEYBOARD_ROW1_X+KEYBOARD_KEY_WIDTH*4, .y = KEYBOARD_Y_START, .label = "5" },
    { .id = '6', KEYBOARD_LABEL_SCALE, .width = KEYBOARD_KEY_WIDTH, .height = KEYBOARD_KEY_HEIGHT, .x = KEYBOARD_ROW1_X+KEYBOARD_KEY_WIDTH*5, .y = KEYBOARD_Y_START, .label = "6" },
    { .id = '7', KEYBOARD_LABEL_SCALE, .width = KEYBOARD_KEY_WIDTH, .height = KEYBOARD_KEY_HEIGHT, .x = KEYBOARD_ROW1_X+KEYBOARD_KEY_WIDTH*6, .y = KEYBOARD_Y_START, .label = "7" },
    { .id = '8', KEYBOARD_LABEL_SCALE, .width = KEYBOARD_KEY_WIDTH, .height = KEYBOARD_KEY_HEIGHT, .x = KEYBOARD_ROW1_X+KEYBOARD_KEY_WIDTH*7, .y = KEYBOARD_Y_START, .label = "8" },
    { .id = '9', KEYBOARD_LABEL_SCALE, .width = KEYBOARD_KEY_WIDTH, .height = KEYBOARD_KEY_HEIGHT, .x = KEYBOARD_ROW1_X+KEYBOARD_KEY_WIDTH*8, .y = KEYBOARD_Y_START, .label = "9" },
    { .id = '0', KEYBOARD_LABEL_SCALE, .width = KEYBOARD_KEY_WIDTH, .height = KEYBOARD_KEY_HEIGHT, .x = KEYBOARD_ROW1_X+KEYBOARD_KEY_WIDTH*9, .y = KEYBOARD_Y_START, .label = "0" },

    { .id = 'q', KEYBOARD_LABEL_SCALE, .width = KEYBOARD_KEY_WIDTH, .height = KEYBOARD_KEY_HEIGHT, .x = KEYBOARD_ROW2_X,             .y = KEYBOARD_Y_START+KEYBOARD_KEY_HEIGHT, .label = "q" },
    { .id = 'w', KEYBOARD_LABEL_SCALE, .width = KEYBOARD_KEY_WIDTH, .height = KEYBOARD_KEY_HEIGHT, .x = KEYBOARD_ROW2_X+KEYBOARD_KEY_WIDTH,   .y = KEYBOARD_Y_START+KEYBOARD_KEY_HEIGHT, .label = "w" },
    { .id = 'e', KEYBOARD_LABEL_SCALE, .width = KEYBOARD_KEY_WIDTH, .height = KEYBOARD_KEY_HEIGHT, .x = KEYBOARD_ROW2_X+KEYBOARD_KEY_WIDTH*2, .y = KEYBOARD_Y_START+KEYBOARD_KEY_HEIGHT, .label = "e" },
    { .id = 'r', KEYBOARD_LABEL_SCALE, .width = KEYBOARD_KEY_WIDTH, .height = KEYBOARD_KEY_HEIGHT, .x = KEYBOARD_ROW2_X+KEYBOARD_KEY_WIDTH*3, .y = KEYBOARD_Y_START+KEYBOARD_KEY_HEIGHT, .label = "r" },
    { .id = 't', KEYBOARD_LABEL_SCALE, .width = KEYBOARD_KEY_WIDTH, .height = KEYBOARD_KEY_HEIGHT, .x = KEYBOARD_ROW2_X+KEYBOARD_KEY_WIDTH*4, .y = KEYBOARD_Y_START+KEYBOARD_KEY_HEIGHT, .label = "t" },
    { .id = 'y', KEYBOARD_LABEL_SCALE, .width = KEYBOARD_KEY_WIDTH, .height = KEYBOARD_KEY_HEIGHT, .x = KEYBOARD_ROW2_X+KEYBOARD_KEY_WIDTH*5, .y = KEYBOARD_Y_START+KEYBOARD_KEY_HEIGHT, .label = "y" },
    { .id = 'u', KEYBOARD_LABEL_SCALE, .width = KEYBOARD_KEY_WIDTH, .height = KEYBOARD_KEY_HEIGHT, .x = KEYBOARD_ROW2_X+KEYBOARD_KEY_WIDTH*6, .y = KEYBOARD_Y_START+KEYBOARD_KEY_HEIGHT, .label = "u" },
    { .id = 'i', KEYBOARD_LABEL_SCALE, .width = KEYBOARD_KEY_WIDTH, .height = KEYBOARD_KEY_HEIGHT, .x = KEYBOARD_ROW2_X+KEYBOARD_KEY_WIDTH*7, .y = KEYBOARD_Y_START+KEYBOARD_KEY_HEIGHT, .label = "i" },
    { .id = 'o', KEYBOARD_LABEL_SCALE, .width = KEYBOARD_KEY_WIDTH, .height = KEYBOARD_KEY_HEIGHT, .x = KEYBOARD_ROW2_X+KEYBOARD_KEY_WIDTH*8, .y = KEYBOARD_Y_START+KEYBOARD_KEY_HEIGHT, .label = "o" },
    { .id = 'p', KEYBOARD_LABEL_SCALE, .width = KEYBOARD_KEY_WIDTH, .height = KEYBOARD_KEY_HEIGHT, .x = KEYBOARD_ROW2_X+KEYBOARD_KEY_WIDTH*9, .y = KEYBOARD_Y_START+KEYBOARD_KEY_HEIGHT, .label = "p" },

    { .id = 'a', KEYBOARD_LABEL_SCALE, .width = KEYBOARD_KEY_WIDTH, .height = KEYBOARD_KEY_HEIGHT, .x = KEYBOARD_ROW3_X,             .y = KEYBOARD_Y_START+KEYBOARD_KEY_HEIGHT*2, .label = "a" },
    { .id = 's', KEYBOARD_LABEL_SCALE, .width = KEYBOARD_KEY_WIDTH, .height = KEYBOARD_KEY_HEIGHT, .x = KEYBOARD_ROW3_X+KEYBOARD_KEY_WIDTH,   .y = KEYBOARD_Y_START+KEYBOARD_KEY_HEIGHT*2, .label = "s" },
    { .id = 'd', KEYBOARD_LABEL_SCALE, .width = KEYBOARD_KEY_WIDTH, .height = KEYBOARD_KEY_HEIGHT, .x = KEYBOARD_ROW3_X+KEYBOARD_KEY_WIDTH*2, .y = KEYBOARD_Y_START+KEYBOARD_KEY_HEIGHT*2, .label = "d" },
    { .id = 'f', KEYBOARD_LABEL_SCALE, .width = KEYBOARD_KEY_WIDTH, .height = KEYBOARD_KEY_HEIGHT, .x = KEYBOARD_ROW3_X+KEYBOARD_KEY_WIDTH*3, .y = KEYBOARD_Y_START+KEYBOARD_KEY_HEIGHT*2, .label = "f" },
    { .id = 'g', KEYBOARD_LABEL_SCALE, .width = KEYBOARD_KEY_WIDTH, .height = KEYBOARD_KEY_HEIGHT, .x = KEYBOARD_ROW3_X+KEYBOARD_KEY_WIDTH*4, .y = KEYBOARD_Y_START+KEYBOARD_KEY_HEIGHT*2, .label = "g" },
    { .id = 'h', KEYBOARD_LABEL_SCALE, .width = KEYBOARD_KEY_WIDTH, .height = KEYBOARD_KEY_HEIGHT, .x = KEYBOARD_ROW3_X+KEYBOARD_KEY_WIDTH*5, .y = KEYBOARD_Y_START+KEYBOARD_KEY_HEIGHT*2, .label = "h" },
    { .id = 'j', KEYBOARD_LABEL_SCALE, .width = KEYBOARD_KEY_WIDTH, .height = KEYBOARD_KEY_HEIGHT, .x = KEYBOARD_ROW3_X+KEYBOARD_KEY_WIDTH*6, .y = KEYBOARD_Y_START+KEYBOARD_KEY_HEIGHT*2, .label = "j" },
    { .id = 'k', KEYBOARD_LABEL_SCALE, .width = KEYBOARD_KEY_WIDTH, .height = KEYBOARD_KEY_HEIGHT, .x = KEYBOARD_ROW3_X+KEYBOARD_KEY_WIDTH*7, .y = KEYBOARD_Y_START+KEYBOARD_KEY_HEIGHT*2, .label = "k" },
    { .id = 'l', KEYBOARD_LABEL_SCALE, .width = KEYBOARD_KEY_WIDTH, .height = KEYBOARD_KEY_HEIGHT, .x = KEYBOARD_ROW3_X+KEYBOARD_KEY_WIDTH*8, .y = KEYBOARD_Y_START+KEYBOARD_KEY_HEIGHT*2, .label = "l" },

    { .id = 'z', KEYBOARD_LABEL_SCALE, .width = KEYBOARD_KEY_WIDTH, .height = KEYBOARD_KEY_HEIGHT, .x = KEYBOARD_ROW4_X,             .y = KEYBOARD_Y_START+KEYBOARD_KEY_HEIGHT*3, .label = "z" },
    { .id = 'x', KEYBOARD_LABEL_SCALE, .width = KEYBOARD_KEY_WIDTH, .height = KEYBOARD_KEY_HEIGHT, .x = KEYBOARD_ROW4_X+KEYBOARD_KEY_WIDTH,   .y = KEYBOARD_Y_START+KEYBOARD_KEY_HEIGHT*3, .label = "x" },
    { .id = 'c', KEYBOARD_LABEL_SCALE, .width = KEYBOARD_KEY_WIDTH, .height = KEYBOARD_KEY_HEIGHT, .x = KEYBOARD_ROW4_X+KEYBOARD_KEY_WIDTH*2, .y = KEYBOARD_Y_START+KEYBOARD_KEY_HEIGHT*3, .label = "c" },
    { .id = 'v', KEYBOARD_LABEL_SCALE, .width = KEYBOARD_KEY_WIDTH, .height = KEYBOARD_KEY_HEIGHT, .x = KEYBOARD_ROW4_X+KEYBOARD_KEY_WIDTH*3, .y = KEYBOARD_Y_START+KEYBOARD_KEY_HEIGHT*3, .label = "v" },
    { .id = 'b', KEYBOARD_LABEL_SCALE, .width = KEYBOARD_KEY_WIDTH, .height = KEYBOARD_KEY_HEIGHT, .x = KEYBOARD_ROW4_X+KEYBOARD_KEY_WIDTH*4, .y = KEYBOARD_Y_START+KEYBOARD_KEY_HEIGHT*3, .label = "b" },
    { .id = 'n', KEYBOARD_LABEL_SCALE, .width = KEYBOARD_KEY_WIDTH, .height = KEYBOARD_KEY_HEIGHT, .x = KEYBOARD_ROW4_X+KEYBOARD_KEY_WIDTH*5, .y = KEYBOARD_Y_START+KEYBOARD_KEY_HEIGHT*3, .label = "n" },
    { .id = 'm', KEYBOARD_LABEL_SCALE, .width = KEYBOARD_KEY_WIDTH, .height = KEYBOARD_KEY_HEIGHT, .x = KEYBOARD_ROW4_X+KEYBOARD_KEY_WIDTH*6, .y = KEYBOARD_Y_START+KEYBOARD_KEY_HEIGHT*3, .label = "m" },
    { .id = ',', KEYBOARD_LABEL_SCALE, .width = KEYBOARD_KEY_WIDTH, .height = KEYBOARD_KEY_HEIGHT, .x = KEYBOARD_ROW4_X+KEYBOARD_KEY_WIDTH*7, .y = KEYBOARD_Y_START+KEYBOARD_KEY_HEIGHT*3, .label = "," },
    { .id = '.', KEYBOARD_LABEL_SCALE, .width = KEYBOARD_KEY_WIDTH, .height = KEYBOARD_KEY_HEIGHT, .x = KEYBOARD_ROW4_X+KEYBOARD_KEY_WIDTH*8, .y = KEYBOARD_Y_START+KEYBOARD_KEY_HEIGHT*3, .label = "." },

    { .id = '\b', KEYBOARD_LABEL_SCALE+1, .width = KEYBOARD_KEY_WIDTH*2, .height = KEYBOARD_KEY_HEIGHT, .x = KEYBOARD_KEY_WIDTH*3, .y = KEYBOARD_Y_START+KEYBOARD_KEY_HEIGHT*4, .label = "\b" },
    { .id = '\n', KEYBOARD_LABEL_SCALE+1, .width = KEYBOARD_KEY_WIDTH*2, .height = KEYBOARD_KEY_HEIGHT, .x = KEYBOARD_KEY_WIDTH*5, .y = KEYBOARD_Y_START+KEYBOARD_KEY_HEIGHT*4, .label = "\x06"  },
};

const InterfaceInputElement_t keypad = { 12, keypad_buttons };
const InterfaceInputElement_t keyboard = { 40, keyboard_buttons };

const InterfaceInputElement_t* keypads[2] = { &keypad, &keyboard };
