#include "gui_elements.h"

#define KEYBOARD_KEY_WIDTH (30)
#define KEYBOARD_KEY_HEIGHT (20)
#define KEYBOARD_X_START (2)
#define KEYBOARD_X_GAP (1)
#define KEYBOARD_ROW1_X (KEYBOARD_X_START)
#define KEYBOARD_ROW2_X (KEYBOARD_X_START+(KEYBOARD_KEY_WIDTH/4))
#define KEYBOARD_ROW3_X (KEYBOARD_X_START+(KEYBOARD_KEY_WIDTH/2))
#define KEYBOARD_ROW4_X (KEYBOARD_X_START+KEYBOARD_KEY_WIDTH)
#define KEYBOARD_Y_START (2)
#define KEYBOARD_Y_GAP (1)
#define KEYBOARD_ROW1_Y (KEYBOARD_Y_START)
#define KEYBOARD_ROW2_Y (KEYBOARD_ROW1_Y+(KEYBOARD_KEY_HEIGHT+KEYBOARD_Y_GAP))
#define KEYBOARD_ROW3_Y (KEYBOARD_ROW1_Y+((KEYBOARD_KEY_HEIGHT+KEYBOARD_Y_GAP)*2))
#define KEYBOARD_ROW4_Y (KEYBOARD_ROW1_Y+((KEYBOARD_KEY_HEIGHT+KEYBOARD_Y_GAP)*3))
#define KEYBOARD_ROW5_Y (KEYBOARD_ROW1_Y+((KEYBOARD_KEY_HEIGHT+KEYBOARD_Y_GAP)*4))

#define BUTTON_WIDTH (64)
#define BUTTON_HEIGHT (56)
#define BUTTON_X_GAP (8)
#define BUTTON_Y_GAP (6)
#define BUTTON_COL1_X (16)
#define BUTTON_COL2_X (BUTTON_COL1_X + ((BUTTON_X_GAP+BUTTON_WIDTH)))
#define BUTTON_COL3_X (BUTTON_COL1_X + ((BUTTON_X_GAP+BUTTON_WIDTH)*2))
#define BUTTON_COL4_X (BUTTON_COL1_X + ((BUTTON_X_GAP+BUTTON_WIDTH)*3))
#define BUTTON_ROW1_Y (1)
#define BUTTON_ROW2_Y (BUTTON_ROW1_Y+BUTTON_Y_GAP+BUTTON_HEIGHT)

const InterfaceButton_t keyboard_buttons[40] =
{
    { '1', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW1_X,             KEYBOARD_ROW1_Y, "1", NULL },
    { '2', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW1_X+KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP,   KEYBOARD_ROW1_Y, "2", NULL },
    { '3', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW1_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*2, KEYBOARD_ROW1_Y, "3", NULL },
    { '4', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW1_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*3, KEYBOARD_ROW1_Y, "4", NULL },
    { '5', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW1_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*4, KEYBOARD_ROW1_Y, "5", NULL },
    { '6', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW1_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*5, KEYBOARD_ROW1_Y, "6", NULL },
    { '7', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW1_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*6, KEYBOARD_ROW1_Y, "7", NULL },
    { '8', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW1_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*7, KEYBOARD_ROW1_Y, "8", NULL },
    { '9', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW1_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*8, KEYBOARD_ROW1_Y, "9", NULL },
    { '0', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW1_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*9, KEYBOARD_ROW1_Y, "0", NULL },

    { 'q', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW2_X,             KEYBOARD_ROW2_Y, "q", NULL },
    { 'w', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW2_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP),   KEYBOARD_ROW2_Y, "w", NULL },
    { 'e', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW2_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*2, KEYBOARD_ROW2_Y, "e", NULL },
    { 'r', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW2_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*3, KEYBOARD_ROW2_Y, "r", NULL },
    { 't', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW2_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*4, KEYBOARD_ROW2_Y, "t", NULL },
    { 'y', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW2_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*5, KEYBOARD_ROW2_Y, "y", NULL },
    { 'u', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW2_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*6, KEYBOARD_ROW2_Y, "u", NULL },
    { 'i', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW2_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*7, KEYBOARD_ROW2_Y, "i", NULL },
    { 'o', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW2_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*8, KEYBOARD_ROW2_Y, "o", NULL },
    { 'p', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW2_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*9, KEYBOARD_ROW2_Y, "p", NULL },

    { 'a', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW3_X,             KEYBOARD_ROW3_Y, "a", NULL },
    { 's', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW3_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP),   KEYBOARD_ROW3_Y, "s", NULL },
    { 'd', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW3_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*2, KEYBOARD_ROW3_Y, "d", NULL },
    { 'f', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW3_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*3, KEYBOARD_ROW3_Y, "f", NULL },
    { 'g', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW3_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*4, KEYBOARD_ROW3_Y, "g", NULL },
    { 'h', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW3_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*5, KEYBOARD_ROW3_Y, "h", NULL },
    { 'j', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW3_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*6, KEYBOARD_ROW3_Y, "j", NULL },
    { 'k', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW3_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*7, KEYBOARD_ROW3_Y, "k", NULL },
    { 'l', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW3_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*8, KEYBOARD_ROW3_Y, "l", NULL },

    { 'z', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW4_X,             KEYBOARD_ROW4_Y, "z", NULL },
    { 'x', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW4_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP),   KEYBOARD_ROW4_Y, "x", NULL },
    { 'c', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW4_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*2, KEYBOARD_ROW4_Y, "c", NULL },
    { 'v', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW4_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*3, KEYBOARD_ROW4_Y, "v", NULL },
    { 'b', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW4_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*4, KEYBOARD_ROW4_Y, "b", NULL },
    { 'n', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW4_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*5, KEYBOARD_ROW4_Y, "n", NULL },
    { 'm', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW4_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*6, KEYBOARD_ROW4_Y, "m", NULL },
    { ',', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW4_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*7, KEYBOARD_ROW4_Y, ",", NULL },
    { '.', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW4_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*8, KEYBOARD_ROW4_Y, ".", NULL },

    { '\b', 3, KEYBOARD_KEY_WIDTH+(KEYBOARD_KEY_WIDTH/2), KEYBOARD_KEY_HEIGHT+(KEYBOARD_KEY_HEIGHT/2), KEYBOARD_KEY_WIDTH*3, KEYBOARD_ROW5_Y, "", &icon_delete },
    { '\n', 3, KEYBOARD_KEY_WIDTH+(KEYBOARD_KEY_WIDTH/2), KEYBOARD_KEY_HEIGHT+(KEYBOARD_KEY_HEIGHT/2), KEYBOARD_KEY_WIDTH*5, KEYBOARD_ROW5_Y, "", &icon_enter },
};

const InterfaceButton_t door_list_buttons[8] =
{
    { IACTION_SELECT_DOOR_1, 2, BUTTON_WIDTH, BUTTON_HEIGHT, BUTTON_COL1_X, BUTTON_ROW1_Y, "1", &icon_door },
    { IACTION_SELECT_DOOR_2, 2, BUTTON_WIDTH, BUTTON_HEIGHT, BUTTON_COL2_X, BUTTON_ROW1_Y, "2", &icon_door },
    { IACTION_SELECT_DOOR_3, 2, BUTTON_WIDTH, BUTTON_HEIGHT, BUTTON_COL3_X, BUTTON_ROW1_Y, "3", &icon_door },
    { IACTION_SELECT_DOOR_4, 2, BUTTON_WIDTH, BUTTON_HEIGHT, BUTTON_COL4_X, BUTTON_ROW1_Y, "4", &icon_door },

    { IACTION_SELECT_DOOR_5, 2, BUTTON_WIDTH, BUTTON_HEIGHT, BUTTON_COL1_X, BUTTON_ROW2_Y, "5", &icon_door },
    { IACTION_SELECT_DOOR_6, 2, BUTTON_WIDTH, BUTTON_HEIGHT, BUTTON_COL2_X, BUTTON_ROW2_Y, "6", &icon_door },
    { IACTION_SELECT_DOOR_7, 2, BUTTON_WIDTH, BUTTON_HEIGHT, BUTTON_COL3_X, BUTTON_ROW2_Y, "7", &icon_door },
    { IACTION_SELECT_DOOR_8, 2, BUTTON_WIDTH, BUTTON_HEIGHT, BUTTON_COL4_X, BUTTON_ROW2_Y, "8", &icon_door },
};

const InterfaceButton_t door_menu_buttons[3] =
{
    { IACTION_BACK,   2, BUTTON_WIDTH, BUTTON_HEIGHT, BUTTON_COL1_X, BUTTON_ROW1_Y, "", &icon_delete },
    { IACTION_OPEN,   2, BUTTON_WIDTH, BUTTON_HEIGHT, BUTTON_COL2_X, BUTTON_ROW1_Y, "", &icon_open },
    { IACTION_CAMERA, 2, BUTTON_WIDTH, BUTTON_HEIGHT, BUTTON_COL3_X, BUTTON_ROW1_Y, "", &icon_bell },
};

const InterfaceInputElement_t keyboard = { 40, keyboard_buttons };
const InterfaceInputElement_t door_list = { 8, door_list_buttons };
const InterfaceInputElement_t door_menu = { 3, door_menu_buttons };

InterfaceInputElement_t *input_layouts[NUM_LAYOUTS] =
{
    &keyboard,
    &door_list,
    &door_menu,
};
