#include "gui_elements.h"

#define KEY_WIDTH (32)
#define KEY_HEIGHT (21)
#define ROW1_X (0)
#define ROW2_X (0)
#define ROW3_X (KEY_WIDTH/2)
#define ROW4_X (KEY_WIDTH/2)
#define KEY_Y (0)

const InterfaceButton_t touch_keyboard[40] =
{
    { '1', 2, KEY_WIDTH, KEY_HEIGHT, ROW1_X,             KEY_Y, "1" },
    { '2', 2, KEY_WIDTH, KEY_HEIGHT, ROW1_X+KEY_WIDTH,   KEY_Y, "2" },
    { '3', 2, KEY_WIDTH, KEY_HEIGHT, ROW1_X+KEY_WIDTH*2, KEY_Y, "3" },
    { '4', 2, KEY_WIDTH, KEY_HEIGHT, ROW1_X+KEY_WIDTH*3, KEY_Y, "4" },
    { '5', 2, KEY_WIDTH, KEY_HEIGHT, ROW1_X+KEY_WIDTH*4, KEY_Y, "5" },
    { '6', 2, KEY_WIDTH, KEY_HEIGHT, ROW1_X+KEY_WIDTH*5, KEY_Y, "6" },
    { '7', 2, KEY_WIDTH, KEY_HEIGHT, ROW1_X+KEY_WIDTH*6, KEY_Y, "7" },
    { '8', 2, KEY_WIDTH, KEY_HEIGHT, ROW1_X+KEY_WIDTH*7, KEY_Y, "8" },
    { '9', 2, KEY_WIDTH, KEY_HEIGHT, ROW1_X+KEY_WIDTH*8, KEY_Y, "9" },
    { '0', 2, KEY_WIDTH, KEY_HEIGHT, ROW1_X+KEY_WIDTH*9, KEY_Y, "0" },

    { 'q', 2, KEY_WIDTH, KEY_HEIGHT, ROW2_X,             KEY_Y+KEY_HEIGHT, "q" },
    { 'w', 2, KEY_WIDTH, KEY_HEIGHT, ROW2_X+KEY_WIDTH,   KEY_Y+KEY_HEIGHT, "w" },
    { 'e', 2, KEY_WIDTH, KEY_HEIGHT, ROW2_X+KEY_WIDTH*2, KEY_Y+KEY_HEIGHT, "e" },
    { 'r', 2, KEY_WIDTH, KEY_HEIGHT, ROW2_X+KEY_WIDTH*3, KEY_Y+KEY_HEIGHT, "r" },
    { 't', 2, KEY_WIDTH, KEY_HEIGHT, ROW2_X+KEY_WIDTH*4, KEY_Y+KEY_HEIGHT, "t" },
    { 'y', 2, KEY_WIDTH, KEY_HEIGHT, ROW2_X+KEY_WIDTH*5, KEY_Y+KEY_HEIGHT, "y" },
    { 'u', 2, KEY_WIDTH, KEY_HEIGHT, ROW2_X+KEY_WIDTH*6, KEY_Y+KEY_HEIGHT, "u" },
    { 'i', 2, KEY_WIDTH, KEY_HEIGHT, ROW2_X+KEY_WIDTH*7, KEY_Y+KEY_HEIGHT, "i" },
    { 'o', 2, KEY_WIDTH, KEY_HEIGHT, ROW2_X+KEY_WIDTH*8, KEY_Y+KEY_HEIGHT, "o" },
    { 'p', 2, KEY_WIDTH, KEY_HEIGHT, ROW2_X+KEY_WIDTH*9, KEY_Y+KEY_HEIGHT, "p" },

    { 'a', 2, KEY_WIDTH, KEY_HEIGHT, ROW3_X,             KEY_Y+KEY_HEIGHT*2, "a" },
    { 's', 2, KEY_WIDTH, KEY_HEIGHT, ROW3_X+KEY_WIDTH,   KEY_Y+KEY_HEIGHT*2, "s" },
    { 'd', 2, KEY_WIDTH, KEY_HEIGHT, ROW3_X+KEY_WIDTH*2, KEY_Y+KEY_HEIGHT*2, "d" },
    { 'f', 2, KEY_WIDTH, KEY_HEIGHT, ROW3_X+KEY_WIDTH*3, KEY_Y+KEY_HEIGHT*2, "f" },
    { 'g', 2, KEY_WIDTH, KEY_HEIGHT, ROW3_X+KEY_WIDTH*4, KEY_Y+KEY_HEIGHT*2, "g" },
    { 'h', 2, KEY_WIDTH, KEY_HEIGHT, ROW3_X+KEY_WIDTH*5, KEY_Y+KEY_HEIGHT*2, "h" },
    { 'j', 2, KEY_WIDTH, KEY_HEIGHT, ROW3_X+KEY_WIDTH*6, KEY_Y+KEY_HEIGHT*2, "j" },
    { 'k', 2, KEY_WIDTH, KEY_HEIGHT, ROW3_X+KEY_WIDTH*7, KEY_Y+KEY_HEIGHT*2, "k" },
    { 'l', 2, KEY_WIDTH, KEY_HEIGHT, ROW3_X+KEY_WIDTH*8, KEY_Y+KEY_HEIGHT*2, "l" },

    { 'z', 2, KEY_WIDTH, KEY_HEIGHT, ROW4_X,             KEY_Y+KEY_HEIGHT*3, "z" },
    { 'x', 2, KEY_WIDTH, KEY_HEIGHT, ROW4_X+KEY_WIDTH,   KEY_Y+KEY_HEIGHT*3, "x" },
    { 'c', 2, KEY_WIDTH, KEY_HEIGHT, ROW4_X+KEY_WIDTH*2, KEY_Y+KEY_HEIGHT*3, "c" },
    { 'v', 2, KEY_WIDTH, KEY_HEIGHT, ROW4_X+KEY_WIDTH*3, KEY_Y+KEY_HEIGHT*3, "v" },
    { 'b', 2, KEY_WIDTH, KEY_HEIGHT, ROW4_X+KEY_WIDTH*4, KEY_Y+KEY_HEIGHT*3, "b" },
    { 'n', 2, KEY_WIDTH, KEY_HEIGHT, ROW4_X+KEY_WIDTH*5, KEY_Y+KEY_HEIGHT*3, "n" },
    { 'm', 2, KEY_WIDTH, KEY_HEIGHT, ROW4_X+KEY_WIDTH*6, KEY_Y+KEY_HEIGHT*3, "m" },
    { ',', 2, KEY_WIDTH, KEY_HEIGHT, ROW4_X+KEY_WIDTH*7, KEY_Y+KEY_HEIGHT*3, "," },
    { '.', 2, KEY_WIDTH, KEY_HEIGHT, ROW4_X+KEY_WIDTH*8, KEY_Y+KEY_HEIGHT*3, "." },

    { '\b', 1, KEY_WIDTH*2, KEY_HEIGHT, KEY_WIDTH*3, KEY_Y+KEY_HEIGHT*4, "DEL" },
    { '\n', 1, KEY_WIDTH*2, KEY_HEIGHT, KEY_WIDTH*5, KEY_Y+KEY_HEIGHT*4, "ENTER" },
};
