#include "gui_elements.h"

#define KEYBOARD_KEY_WIDTH (30)
#define KEYBOARD_KEY_HEIGHT (20)
#define KEYBOARD_X_START (2)
#define KEYBOARD_X_GAP (1)
#define KEYBOARD_ROW1_X (KEYBOARD_X_START)
#define KEYBOARD_ROW2_X (KEYBOARD_X_START+(KEYBOARD_KEY_WIDTH/4))
#define KEYBOARD_ROW3_X (KEYBOARD_X_START+(KEYBOARD_KEY_WIDTH/2))
#define KEYBOARD_ROW4_X (KEYBOARD_X_START+KEYBOARD_KEY_WIDTH)
#define KEYBOARD_Y_START (2)
#define KEYBOARD_Y_GAP (1)
#define KEYBOARD_ROW1_Y (KEYBOARD_Y_START)
#define KEYBOARD_ROW2_Y (KEYBOARD_ROW1_Y+(KEYBOARD_KEY_HEIGHT+KEYBOARD_Y_GAP))
#define KEYBOARD_ROW3_Y (KEYBOARD_ROW1_Y+((KEYBOARD_KEY_HEIGHT+KEYBOARD_Y_GAP)*2))
#define KEYBOARD_ROW4_Y (KEYBOARD_ROW1_Y+((KEYBOARD_KEY_HEIGHT+KEYBOARD_Y_GAP)*3))
#define KEYBOARD_ROW5_Y (KEYBOARD_ROW1_Y+((KEYBOARD_KEY_HEIGHT+KEYBOARD_Y_GAP)*4))

#define BUTTON_WIDTH (64)
#define BUTTON_HEIGHT (56)
#define BUTTON_X_GAP (8)
#define BUTTON_Y_GAP (6)
#define BUTTON_COL1_X (16)
#define BUTTON_COL2_X (BUTTON_COL1_X + ((BUTTON_X_GAP+BUTTON_WIDTH)))
#define BUTTON_COL3_X (BUTTON_COL1_X + ((BUTTON_X_GAP+BUTTON_WIDTH)*2))
#define BUTTON_COL4_X (BUTTON_COL1_X + ((BUTTON_X_GAP+BUTTON_WIDTH)*3))
#define BUTTON_ROW1_Y (1)
#define BUTTON_ROW2_Y (BUTTON_ROW1_Y+BUTTON_Y_GAP+BUTTON_HEIGHT)

InterfaceButton_t keyboard_buttons[40] =
{
    { true, '1', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW1_X,             KEYBOARD_ROW1_Y, "1", NULL },
    { true, '2', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW1_X+KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP,   KEYBOARD_ROW1_Y, "2", NULL },
    { true, '3', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW1_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*2, KEYBOARD_ROW1_Y, "3", NULL },
    { true, '4', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW1_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*3, KEYBOARD_ROW1_Y, "4", NULL },
    { true, '5', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW1_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*4, KEYBOARD_ROW1_Y, "5", NULL },
    { true, '6', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW1_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*5, KEYBOARD_ROW1_Y, "6", NULL },
    { true, '7', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW1_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*6, KEYBOARD_ROW1_Y, "7", NULL },
    { true, '8', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW1_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*7, KEYBOARD_ROW1_Y, "8", NULL },
    { true, '9', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW1_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*8, KEYBOARD_ROW1_Y, "9", NULL },
    { true, '0', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW1_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*9, KEYBOARD_ROW1_Y, "0", NULL },

    { true, 'q', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW2_X,             KEYBOARD_ROW2_Y, "q", NULL },
    { true, 'w', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW2_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP),   KEYBOARD_ROW2_Y, "w", NULL },
    { true, 'e', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW2_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*2, KEYBOARD_ROW2_Y, "e", NULL },
    { true, 'r', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW2_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*3, KEYBOARD_ROW2_Y, "r", NULL },
    { true, 't', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW2_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*4, KEYBOARD_ROW2_Y, "t", NULL },
    { true, 'y', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW2_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*5, KEYBOARD_ROW2_Y, "y", NULL },
    { true, 'u', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW2_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*6, KEYBOARD_ROW2_Y, "u", NULL },
    { true, 'i', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW2_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*7, KEYBOARD_ROW2_Y, "i", NULL },
    { true, 'o', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW2_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*8, KEYBOARD_ROW2_Y, "o", NULL },
    { true, 'p', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW2_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*9, KEYBOARD_ROW2_Y, "p", NULL },

    { true, 'a', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW3_X,             KEYBOARD_ROW3_Y, "a", NULL },
    { true, 's', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW3_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP),   KEYBOARD_ROW3_Y, "s", NULL },
    { true, 'd', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW3_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*2, KEYBOARD_ROW3_Y, "d", NULL },
    { true, 'f', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW3_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*3, KEYBOARD_ROW3_Y, "f", NULL },
    { true, 'g', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW3_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*4, KEYBOARD_ROW3_Y, "g", NULL },
    { true, 'h', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW3_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*5, KEYBOARD_ROW3_Y, "h", NULL },
    { true, 'j', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW3_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*6, KEYBOARD_ROW3_Y, "j", NULL },
    { true, 'k', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW3_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*7, KEYBOARD_ROW3_Y, "k", NULL },
    { true, 'l', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW3_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*8, KEYBOARD_ROW3_Y, "l", NULL },

    { true, 'z', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW4_X,             KEYBOARD_ROW4_Y, "z", NULL },
    { true, 'x', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW4_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP),   KEYBOARD_ROW4_Y, "x", NULL },
    { true, 'c', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW4_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*2, KEYBOARD_ROW4_Y, "c", NULL },
    { true, 'v', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW4_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*3, KEYBOARD_ROW4_Y, "v", NULL },
    { true, 'b', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW4_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*4, KEYBOARD_ROW4_Y, "b", NULL },
    { true, 'n', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW4_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*5, KEYBOARD_ROW4_Y, "n", NULL },
    { true, 'm', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW4_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*6, KEYBOARD_ROW4_Y, "m", NULL },
    { true, ',', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW4_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*7, KEYBOARD_ROW4_Y, ",", NULL },
    { true, '.', 2, KEYBOARD_KEY_WIDTH, KEYBOARD_KEY_HEIGHT, KEYBOARD_ROW4_X+(KEYBOARD_KEY_WIDTH+KEYBOARD_X_GAP)*8, KEYBOARD_ROW4_Y, ".", NULL },

    { true, '\b', 3, KEYBOARD_KEY_WIDTH+(KEYBOARD_KEY_WIDTH/2), KEYBOARD_KEY_HEIGHT+(KEYBOARD_KEY_HEIGHT/2), KEYBOARD_KEY_WIDTH*3, KEYBOARD_ROW5_Y, "", &icon_delete },
    { true, '\n', 3, KEYBOARD_KEY_WIDTH+(KEYBOARD_KEY_WIDTH/2), KEYBOARD_KEY_HEIGHT+(KEYBOARD_KEY_HEIGHT/2), KEYBOARD_KEY_WIDTH*5, KEYBOARD_ROW5_Y, "", &icon_enter },
};

InterfaceButton_t door_list_buttons[8] =
{
    { false, IACTION_SELECT_DOOR_1, 1, BUTTON_WIDTH, BUTTON_HEIGHT, BUTTON_COL1_X, BUTTON_ROW1_Y, "1", &icon_door },
    { false, IACTION_SELECT_DOOR_2, 1, BUTTON_WIDTH, BUTTON_HEIGHT, BUTTON_COL2_X, BUTTON_ROW1_Y, "2", &icon_door },
    { false, IACTION_SELECT_DOOR_3, 1, BUTTON_WIDTH, BUTTON_HEIGHT, BUTTON_COL3_X, BUTTON_ROW1_Y, "3", &icon_door },
    { false, IACTION_SELECT_DOOR_4, 1, BUTTON_WIDTH, BUTTON_HEIGHT, BUTTON_COL4_X, BUTTON_ROW1_Y, "4", &icon_door },

    { false, IACTION_SELECT_DOOR_5, 1, BUTTON_WIDTH, BUTTON_HEIGHT, BUTTON_COL1_X, BUTTON_ROW2_Y, "5", &icon_door },
    { false, IACTION_SELECT_DOOR_6, 1, BUTTON_WIDTH, BUTTON_HEIGHT, BUTTON_COL2_X, BUTTON_ROW2_Y, "6", &icon_door },
    { false, IACTION_SELECT_DOOR_7, 1, BUTTON_WIDTH, BUTTON_HEIGHT, BUTTON_COL3_X, BUTTON_ROW2_Y, "7", &icon_door },
    { false, IACTION_SELECT_DOOR_8, 1, BUTTON_WIDTH, BUTTON_HEIGHT, BUTTON_COL4_X, BUTTON_ROW2_Y, "8", &icon_door },
};

const InterfaceButton_t door_menu_buttons[3] =
{
    { true, IACTION_BACK,   2, BUTTON_WIDTH, BUTTON_HEIGHT, BUTTON_COL1_X, BUTTON_ROW1_Y, "", &icon_delete },
    { true, IACTION_OPEN,   2, BUTTON_WIDTH, BUTTON_HEIGHT, BUTTON_COL2_X, BUTTON_ROW1_Y, "", &icon_open },
    { true, IACTION_CAMERA, 2, BUTTON_WIDTH, BUTTON_HEIGHT, BUTTON_COL3_X, BUTTON_ROW1_Y, "", &icon_bell },
};


InterfaceInputElement_t input_layouts[NUM_LAYOUTS] =
{
    { false, ILAYOUT_KEYBOARD, 40, keyboard_buttons },
    { false, ILAYOUT_DOOR_LIST, 8, door_list_buttons },
    { false, ILAYOUT_DOOR_ACTIONS, 3, door_menu_buttons },
};

void gui_update_door_button(uint8_t index, bool active, char *name)
{
    door_list_buttons[index].active = active;

    if (active)
    {
        strncpy(door_list_buttons[index].label, name, UNIT_NAME_MAX_LEN);
    }

    input_layouts[ILAYOUT_DOOR_LIST].dirty = true;

    printf("Updated door button index %u to status %s with name %s.\n", index, active ? "Active" : "Inactive", name);
}
